version: '3'

services:
  web:
    build: .
    container_name: web
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./site:/var/www/html
      - ./site/apache2/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./site/sql:/docker-entrypoint-initdb.d
    restart: always

  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./site/sql:/docker-entrypoint-initdb.d

